site_name: CEINMS-RT 复现报告
site_author: Qiucheng Zhao

use_directory_urls: false

theme:
  name: material
  language: zh                 # 中文界面
  palette:
    primary: indigo            # 主题色（深蓝色，很有学术感）
    accent: blue
  features:
    - navigation.tabs          # 顶部导航栏
    - navigation.top           # 返回顶部按钮
    - toc.integrate            # 将目录集成到左侧

# 导航栏结构
nav:
  - 首页: index.md
  - 核心算法复现: CEINMS-RT-Core.md
  - 参数校准算法: Calibration.md
  - Linux上的docker部署: CEINMS-RT-docker.md

# 开启 LaTeX 公式和代码高亮支持
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js